import { createContext, useState, type ReactNode } from 'react';

export type Language = 'ua' | 'en';

const translations = {
  ua: {
    navHome: 'Головна',
    navJobs: 'Вакансії',
    navEmployers: 'Роботодавцям',
    navContacts: 'Контакти',
    findJob: 'Знайти роботу',
    findEmployee: 'Знайти працівника',
    heroTitle: 'Знайди роботу. Знайди працівника.',
    heroHighlight: 'Працюй у Європі.',
    heroSubtitle: 'Платформа прямих контактів між роботодавцями та шукачами без зайвих посередників.',
    footerDesc: 'Платформа для пошуку надійної роботи та перевірених працівників у Європі.',
    rights: 'Всі права захищені.',
    forCandidates: 'Кандидатам',
    forEmployers: 'Роботодавцям',
    categoriesTitle: 'Популярні категорії',
    employersTitle: 'Потрібні працівники?',
    employersText: 'Звʼяжіться з нами для розміщення вакансій.',
    contactUs: 'Контакти',
    allJobsTitle: 'Усі вакансії',
    partnerJobsTitle: 'Вакансії',
    loadingText: 'Завантаження...',
    loadError: 'Сталася помилка при завантаженні даних.',
    retryBtn: 'Спробувати ще раз',
    noJobsFound: 'Вакансій не знайдено.',
    searchPlaceholder: 'Пошук за назвою вакансії...',
    allCategories: 'Усі категорії',
    contactsTitle: 'Звʼязатися з нами',
    nameLabel: 'Імʼя',
    contactLabel: 'Телефон або Telegram',
    messageLabel: 'Повідомлення (опційно)',
    submitBtn: 'Надіслати заявку',
    submittingBtn: 'Надсилання...',
    nameError: 'Імʼя має містити мінімум 2 символи',
    contactError: 'Введіть коректний номер телефону (+380...) або нік у Telegram (@username)',
    messageError: 'Повідомлення не може перевищувати 500 символів',
    successMsg: 'Дякуємо! Вашу заявку успішно надіслано.',
    submitErrorMsg: 'Не вдалося надіслати заявку. Спробуйте ще раз.',
    sendAnotherBtn: 'Надіслати ще одну',
    employerContactsTitle: 'Заявка для роботодавців',
    employerNameLabel: 'Компанія / Контактна особа',
    employerMessagePlaceholder: 'Опишіть вимоги до кандидатів, вакансії та кількість працівників...',
    closeModalBtn: 'Зрозуміло',
    privacyTitle: 'Політика конфіденційності',
    privacyContent: 'Платформа VV Work обробляє персональні дані кандидатів і роботодавців виключно з метою працевлаштування та рекрутингу відповідно до законодавства ЄС (GDPR). Ми не передаємо ваші дані стороннім особам без вашої згоди.',
    termsTitle: 'Умови використання',
    termsContent: 'Користуючись платформою VV Work, ви погоджуєтеся надавати правдиву інформацію про вакансії та свій професійний досвід. Платформа є посередником між кандидатами та прямими роботодавцями.',
    workingHours: 'Пн-Пт: 09:00 - 18:00',
    sphereLabel: 'Сфера:',
    categoriesSubtitle: 'Оберіть напрямок для швидкого пошуку вакансій',
    applyBtn: 'Відгукнутися',
    verifiedBadge: 'Перевірено VV Work',
    activePositions: 'активних вакансій',
    partnerProfileBadge: 'Профіль партнера',
    resetFiltersBtn: 'Скинути всі фільтри',
    candidateSubtitle: 'Залиште контакти, і ми допоможемо підібрати перевірену вакансію.',
    employerSubtitle: 'Заповніть заявку, і менеджер звʼяжеться для узгодження вакансії.',
    candidateNamePlaceholder: "Ваше ім'я та прізвище",
    employerNamePlaceholder: 'ТОВ «Логістик Плюс» або Іван Петров',
    contactPlaceholder: '+380... або @username',
    candidateMessageLabel: 'Повідомлення (опційно)',
    employerMessageLabel: 'Опис вакансії / потреби',
    candidateMessagePlaceholder: 'Коротко опишіть ваш досвід або запитання...',
    employerSubmitBtn: 'Подати заявку на підбір',
    catLogistics: 'Логістика та склади',
    catProduction: 'Виробництво та заводи',
    catConstruction: 'Будівництво та монтаж',
    catHospitality: 'Готельно-ресторанна справа',
    catAgriculture: 'Сільське господарство',
    catTransport: 'Транспорт та водії',
    pageTitleHome: 'VV Work - Головна',
    pageTitleJobs: 'VV Work - Вакансії',
    pageTitleContacts: 'VV Work - Контакти',
    pageTitleDefault: 'VV Work — Робота в Європі',
  },
  en: {
    navHome: 'Home',
    navJobs: 'Jobs',
    navEmployers: 'Employers',
    navContacts: 'Contacts',
    findJob: 'Find Job',
    findEmployee: 'Hire Talent',
    heroTitle: 'Find jobs. Hire specialists.',
    heroHighlight: 'Work across Europe.',
    heroSubtitle: 'Direct connection platform between candidates and verified European employers.',
    footerDesc: 'Platform for finding reliable jobs and verified employees across Europe.',
    rights: 'All rights reserved.',
    forCandidates: 'For Candidates',
    forEmployers: 'For Employers',
    categoriesTitle: 'Popular Categories',
    employersTitle: 'Need Employees?',
    employersText: 'Contact us to post your job openings.',
    contactUs: 'Contacts',
    allJobsTitle: 'All Vacancies',
    partnerJobsTitle: 'Vacancies',
    loadingText: 'Loading...',
    loadError: 'Failed to load jobs data.',
    retryBtn: 'Retry',
    noJobsFound: 'No vacancies found.',
    searchPlaceholder: 'Search jobs by title...',
    allCategories: 'All categories',
    contactsTitle: 'Contact Us',
    nameLabel: 'Name',
    contactLabel: 'Phone or Telegram',
    messageLabel: 'Message (optional)',
    submitBtn: 'Submit Application',
    submittingBtn: 'Submitting...',
    nameError: 'Name must be at least 2 characters long',
    contactError: 'Enter a valid phone number (+380...) or Telegram username (@username)',
    messageError: 'Message cannot exceed 500 characters',
    successMsg: 'Thank you! Your application has been submitted successfully.',
    submitErrorMsg: 'Failed to submit application. Please try again.',
    sendAnotherBtn: 'Send another',
    employerContactsTitle: 'Employer Inquiry',
    employerNameLabel: 'Company / Contact Person',
    employerMessagePlaceholder: 'Describe candidate requirements, open positions, and headcount...',
    closeModalBtn: 'Got it',
    privacyTitle: 'Privacy Policy',
    privacyContent: 'VV Work platform processes personal data of candidates and employers strictly for employment and recruitment purposes in compliance with EU regulations (GDPR). We never transfer your data to third parties without consent.',
    termsTitle: 'Terms of Service',
    termsContent: 'By using VV Work, you agree to provide accurate information regarding vacancies and qualifications. The platform acts as a bridge between candidates and direct European employers.',
    workingHours: 'Mon-Fri: 09:00 - 18:00',
    sphereLabel: 'In:',
    categoriesSubtitle: 'Choose an industry for quick job discovery',
    applyBtn: 'Apply Now',
    verifiedBadge: 'VV Work Verified',
    activePositions: 'active positions',
    partnerProfileBadge: 'Partner Profile',
    resetFiltersBtn: 'Clear all filters',
    candidateSubtitle: 'Leave your details and we will help you find a verified job.',
    employerSubtitle: 'Submit a request and our recruitment manager will contact you.',
    candidateNamePlaceholder: 'Your full name',
    employerNamePlaceholder: 'LLC Logistics Plus or John Doe',
    contactPlaceholder: '+... or @username',
    candidateMessageLabel: 'Message (optional)',
    employerMessageLabel: 'Hiring details',
    candidateMessagePlaceholder: 'Briefly describe your background or question...',
    employerSubmitBtn: 'Submit Hiring Request',
    catLogistics: 'Logistics & Warehouses',
    catProduction: 'Manufacturing & Plants',
    catConstruction: 'Construction & Installation',
    catHospitality: 'Hospitality & HoReCa',
    catAgriculture: 'Agriculture & Farming',
    catTransport: 'Transport & Driving',
    pageTitleHome: 'VV Work - Home',
    pageTitleJobs: 'VV Work - Jobs',
    pageTitleContacts: 'VV Work - Contacts',
    pageTitleDefault: 'VV Work — Jobs in Europe',
  },
} satisfies Record<Language, unknown>;

export type Translations = typeof translations.ua;

export interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: Translations;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined); // eslint-disable-line

function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('ua');

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export default LanguageProvider;